# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy dotnet core project to Azure Function App

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './AzureFunctionsPlaywrightDeploymentTest' # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '6.0.x' # set this to the dotnet version to use
  FUNCTIONS_APP_NAME: 'azure-functions-playwright-deployment-test'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v2

      - name: Setup .NET 5
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: 'Setup Functions Core Tools'
        run: |
          npm i -g azure-functions-core-tools@4 --unsafe-perm true

      - name: 'Build Application'
        shell: bash
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          dotnet publish --configuration Release --output ./output
          popd

      - name: 'Zip Build Output'
        shell: bash
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
          zip -r ../output.zip .
          zipinfo ../output.zip
          popd
        
      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: '{{ env.FUNCTIONS_APP_NAME }}'
          slot-name: 'Production'
          package: './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output.zip'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
